
#nullable enable

namespace Gemini
{
    /// <summary>
    /// Tool that executes code generated by the model, and automatically returns<br/>
    /// the result to the model.<br/>
    /// See also `ExecutableCode` and `CodeExecutionResult` which are only generated<br/>
    /// when using this tool.
    /// </summary>
    public sealed partial class CodeExecution
    {

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::System.Text.Json.Serialization.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();
    }
}